### ISSUE TITLE
account_management failing on newer systems

### ISSUE THREAD

**Issue by cb371j** [DMTF/Redfish-Usecase-Checkers#39]
the password in account_management needs at least one special character

**Comment by billdodd** [comment]
That requirement will vary by vendor implementation (as will the set of acceptable special characters, I expect).

The best approach may be to add command-line options for the test_username and test_password to override the builtin values.

**Comment by mraineri** [comment]
If possible, I would like to see if this type of restriction can be discoverable to avoid having users pass in parameters on a system by system basis... Will need to think this one through a bit more...

**Comment by mraineri** [comment]
@cb371j please try out the latest version of the usecase checkers. Since I don't have access to the specific service you have that's failing, I can't 100% determine if the change I made addresses this, but it looks good to me on the services I have available to me. If the issue persists, please reopen the issue.
