### ISSUE TITLE
power_control.py PowerCycle with host off expects power up, but should it?

### ISSUE THREAD

**Issue by generatz** [DMTF/Redfish-Usecase-Checkers#63]
When I run powercycle.py, the last two reset types are, in sequential order:
GracefulShutdown
PowerCycle

This test fails in the PowerCycle stage when the host state is initially in the power off state (because of the preceding GracefulShutdown) and then the host does not power up as expected by the test.

I suspect this is a test issue because in the case of IPMI, the PowerCycle command should not power up from the power off state:
![image](https://user-images.githubusercontent.com/6298273/200894681-2ad1eb10-04c7-45a1-8411-e9adefeafcd2.png)

Is the redfish design specification (sorry, I don't know where to check) consistent with the IPMI specification? If so, the test needs to be updated.

**Comment by mraineri** [comment]
Redfish moved beyond that definition from IPMI. A user could be issuing a power cycle against many systems to bring them back online. In this case, the user really just wants to get all of their systems back up from a fresh start, and failing requests because a system is off is a poor user experience.

**Comment by generatz** [comment]
Makes sense to me. It's unfortunate IPMI didn't do it this way. Thanks.
