### ISSUE TITLE
Manager Ethernet Interface Checker -  interface_uri_pattern on get_manager_ethernet_interface in managers.py in redfish_utilities

### ISSUE THREAD

**Issue by leoprovido** [DMTF/Redfish-Usecase-Checkers#65]
Hi @mraineri ,

For Manager Ethernet Interface Checker, validator has a dependency on get_manager_ethernet_interface in managers.py in redfish_utilities that hardcodes interface_uri_pattern, which does not work on the device I have.

I changed the interface_uri_pattern to match the @odata.ids of the members in the EthernetInterfaceCollection I receive from the Redfish service on the device I have, and the Manager Ethernet Interface Checker completed the validation.

![image](https://github.com/DMTF/Redfish-Usecase-Checkers/assets/47441723/e0c927ff-c47e-47e7-9ca5-f60bf07fcdc8)

Is the hardcoded interface_uri_pattern on get_manager_ethernet_interface in managers.py in redfish_utilities the the only valid pattern? I wanted to ask this because I'm not sure whether the @odata.ids of the members in the EthernetInterfaceCollection I receive from the Redfish service on the device I have is correctly set.

Thanks,
Leo

**Comment by mraineri** [comment]
Yes, this was intentional. The tools in redfish_utilities for the "manager" APIs are to configure a management controller. If the EthernetInterface resources are under "Systems", then that would represent a host system (and not the BMC).

There are other places where EthernetInterface resources can be found, such as under Systems; having it there is completely valid. However, the reason we focused on this for the use case checker is because it would seem more reliable that there are EthernetInterface resources for managers present; the Redfish service is ultimately hosted on something modeled as a Manager resource, and you'd configure its network configuration from the EthernetInterface resources subordinate to that Manager resource.

So, for your device, do you not allow a user to configure the IP address of the Redfish service? Are the EthernetInterface resources under System really for the system being managed? Or is your device something that combines a manager and system into one and it becomes hard to split the difference?

**Comment by mraineri** [comment]
Closing; from the last comments the service's network configurations really need to be under /redfish/v1/Managers (and not Systems).
